### ISSUE TITLE
Сделать русскоязычные экспортируемые методы

### ISSUE THREAD

**Issue by arkuznetsov** [leemuar/yandexmq-sdk-1c#1]
У нас же весь код на русском, а тут переключаться приходится! :-(
Можно даже не менять существующие, а добавить русскоязычные методы-обертки!

**Comment by leemuar** [comment]
Готово!

Добавлены русскоязычные методы:

    СписокОчередей
    ОчиститьОчередь
    СоздатьОчередь
    УдалитьОчередь
    ПолучитьUrlОчереди
    ПолучитьАтрибутыОчереди
    УстановитьАтрибутыОчереди
    ОтправитьСообщение
    ПолучитьСообщение
    УдалитьСообщение
    ИзменитьВидимостьСообщения

и их братья-аналоги с суффиксом -Ответ, возвращающие детальные данные http-ответа:

    СписокОчередейОтвет
    ОчиститьОчередьОтвет
    СоздатьОчередьОтвет
    УдалитьОчередьОтвет
    ПолучитьUrlОчередиОтвет
    ПолучитьАтрибутыОчередиОтвет
    УстановитьАтрибутыОчередиОтвет
    ОтправитьСообщениеОтвет
    ПолучитьСообщениеОтвет
    УдалитьСообщениеОтвет
    ИзменитьВидимостьСообщенияОтвет
